services:
  - type: web
    name: koton-game-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGINS
        value: https://game-hazel-six-44.vercel.app
